resources:
  repositories:
    - repository: PlaywrightInit.git       # A local alias for the repo in your pipeline
      type: git                   # Repository type
      name: FirstCICDProject/PlaywrightInit.git # Format: <ProjectName>/<RepoName>
      ref: refs/heads/main
trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:

# ------------------------------
# 1️⃣ Build Java project with Maven
# ------------------------------
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'clean package -U'

# ------------------------------
# 2️⃣ Publish the WAR artifact
# ------------------------------
- task: CopyFiles@2
  inputs:
    Contents: '**/*.war'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'warfile'
    publishLocation: 'Container'

# ------------------------------
# 3️⃣ Install Node.js (for Playwright)
# ------------------------------
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Use Node.js 18.x'

# ------------------------------
# 4️⃣ Install npm packages
# ------------------------------
- script: npm install
  displayName: 'Install npm packages'

# ------------------------------
# 5️⃣ Install Playwright browsers
# ------------------------------
- script: npx playwright install
  displayName: 'Install Playwright browsers'
